name: Tarea Programada para subir NIVEL

on:
  schedule:
  
    - cron: '0 14 * * 4'
  workflow_dispatch:

jobs:
  trigger-level-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al endpoint de 'Subir de Nivel'
        run: |
          curl -X POST "${{ secrets.API_URL }}/api/jobs/trigger-level-notifications" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          --fail